### ISSUE TITLE
Unsupported manifest version: 3

### ISSUE THREAD

**Issue by 86135** [dagoyounger/codemao-browse-enhanced#1]
应该是manifest_version设置成了3。。

**Comment by dagoyounger** [comment]
没问题的，manifest_version 3是chrome前一段时间才支持的最新版本，安装最新版chrome一定是可以的

**Comment by 86135** [comment]
我用的是firefox...

**Comment by 86135** [comment]
不过不支持firefox。。。就像我的小项目不支持chrome

**Comment by dagoyounger** [comment]
chrome市场份额大，用户多（
